spring:
  application:
    name: web-two
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev

server:
  port: 18992

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



# 配置swagger
swagger:
    enabled: true
    base-package: com.web
    title: web-two
    version: 1.0.0.SNAPSHOT
    description: 管理后端服务
    contact:
        name: web-two



