spring:
  application:
    name: web-two
  profiles:
      active: @profileActive@
  #============================== ZIPKIN 调用链，开发时可注掉 ==================================
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0  #zipkin采集率  0.1表示 10%采集率

server:
  port: 18992



mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



# 配置swagger
swagger:
    enabled: true
    base-package: com.web
    title: web-two
    version: 1.0.0.SNAPSHOT
    description: 管理后端服务
    contact:
        name: web-two

feign:
  hystrix:
    enabled: true      #启动断路器先关了要用自己开

