 #开发环境
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.45.172:3306/test?useSSL=false&zeroDateTimeBehavior=convertToNull
    username: dpm
    password: FUMEIYU!_dpm!_2017!