spring:
  application:
    name: web-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev

server:
  port: 18991

feign:
  hystrix:
    enabled: true      #启动断路器先关了要用自己开







