#生产环境
spring:
  profiles: prd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.220.11:3306/kevintest?useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: mysql